In [2]:
import numpy as np

In [6]:
# 假设文件名为 'data.npz'
file_path = 'camera_info.npz'

# 加载 .npz 文件
data = np.load(file_path)

# 查看文件中存储的数组名称
print(data.files)

# 访问其中一个数组
# array1 = data['array_name1']
# print(array1)
# print(data['camera_matrix'])
for file in data.files:
    print(file)
#     print(data[file].shape)
    print(data[file])
    print('-----------------')

['gripper_extrinsic_calibration', 'gripper_intrinsics', 'static_extrinsic_calibration', 'static_intrinsics']
gripper_extrinsic_calibration
(4, 4)
[[-1.24030892e-02 -8.41635743e-01  5.39903175e-01 -1.04698349e-01]
 [ 9.99923049e-01 -1.03080524e-02  6.90218095e-03  8.43055337e-03]
 [-2.43771974e-04  5.39947238e-01  8.41698830e-01 -1.46558869e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
-----------------
gripper_intrinsics


ValueError: Object arrays cannot be loaded when allow_pickle=False